In [1]:
import torch

In [18]:
a = torch.randn(2, 3, 2)
c = torch.randn(2, 2, 2)

In [19]:
a[0,:,:]

tensor([[-0.7812, -0.2236],
        [ 0.3610,  1.0156],
        [ 0.3096, -1.2091]])

In [20]:
b = torch.randn(2)
b

tensor([-0.9222,  0.3869])

In [21]:
(a @ c + b) == ((a @ c) + b)

tensor([[[True, True],
         [True, True],
         [True, True]],

        [[True, True],
         [True, True],
         [True, True]]])

In [26]:
e = a @ c

torch.Size([2, 3, 2]) torch.Size([2, 2, 2]) torch.Size([2, 3, 2])


In [27]:
a = torch.randn(3, 2)
a

tensor([[ 1.1286,  1.0004],
        [-0.6336, -1.3158],
        [-0.5244,  1.1885]])

In [31]:
g = a.fill_(3)
print(g, '\n',a)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]]) 
 tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
